apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netflix-deployment
  name: netflix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: pramod858/netflix:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netflix
    k8s-app: netflix
  name: netflix
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: netflix